# Generated by Django 5.2.9 on 2025-12-12 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на проект')),
                ('image_class', models.CharField(blank=True, default='case-card__image--default', max_length=50, verbose_name='CSS класс изображения')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
            },
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название компетенции')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon_class', models.CharField(blank=True, default='competency-card__icon--default', max_length=50, verbose_name='CSS класс иконки')),
            ],
            options={
                'verbose_name': 'Компетенция',
                'verbose_name_plural': 'Компетенции',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='CaseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='Название тега')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='app.case')),
            ],
            options={
                'verbose_name': 'Тег кейса',
                'verbose_name_plural': 'Теги кейсов',
            },
        ),
        migrations.CreateModel(
            name='CompetencyTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_name', models.CharField(max_length=50, verbose_name='Название технологии')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techs', to='app.competency')),
            ],
            options={
                'verbose_name': 'Технология компетенции',
                'verbose_name_plural': 'Технологии компетенций',
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.CharField(max_length=100, verbose_name='Особенность')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='app.service')),
            ],
            options={
                'verbose_name': 'Особенность услуги',
                'verbose_name_plural': 'Особенности услуг',
            },
        ),
    ]
